import { FC } from 'react';
import React from 'react';
import ReactDOM from 'react-dom/client';

interface Prop {
  title:string,
  content?:string,
  name?:string,
  rel?:string
}


export const HeaderMod: React.FC<Prop> = (props) =>{
	return(
	
		<header>
			<title>{props.title}</title>
			<meta name={props.name != null ? props.name : 'description'} content={props.content != null ? props.content : 'Generated by create next app'}/>
		</header>

	);
};
